# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
	# check these on https://fabricmc.net/develop

minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version = 3.2.1+26.2
maven_group = me.emafire003.dev
archives_base_name = coloredglowlib

# Dependencies
fabric_api_version=0.155.2+26.2
cca_version = 8.0.1

#Soft Dependencies
fabricperms_version=0.7.0

