# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
	# check these on https://fabricmc.net/develop

minecraft_version=1.21.11
loader_version=0.18.4
loom_version=1.15-SNAPSHOT

# Mod Properties
mod_version = 3.2.1+1.21.11
maven_group = me.emafire003.dev
archives_base_name = coloredglowlib

# Dependencies
fabric_version=0.141.3+1.21.11
cca_version = 7.3.1

#Soft Dependencies
fabricperms_version=0.6.1

